name: DZEconomy
version: 1.0.0
main: online.demonzdevelopment.DZEconomy
api-version: '1.21'
author: DemonzDevelopment
description: Multi-currency economy plugin with rank-based permissions
softdepend: [PlaceholderAPI, LuckPerms]

commands:
  money:
    description: Money currency commands
    usage: /money [balance|send|request|add|accept|deny|help]
  mobcoin:
    description: MobCoin currency commands
    usage: /mobcoin [balance|send|request|add|accept|deny|help]
  gem:
    description: Gem currency commands
    usage: /gem [balance|send|request|add|accept|deny|help]
  economy:
    description: Convert between currencies
    usage: /economy <from> <to> <amount>
  dzeconomy:
    description: Admin commands
    usage: /dzeconomy [reload|debug]
    aliases: [dze, dzeco]

permissions:
  dzeconomy.admin:
    description: Access to admin commands
    default: op
  dzeconomy.add:
    description: Add currency to players
    default: op
  dzeconomy.default:
    description: Default rank permissions
    default: true